apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-k8s-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: consul-k8s-sa
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: consul
      component: server
  template:
    metadata:
      labels:
        app: consul
        component: server
    spec:
      serviceAccountName: consul-k8s-sa
      containers:
      - name: consul
        image: consul:1.2.3
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        command:
          - "/bin/sh"
          - "-ec"
          - |
            exec /bin/consul agent \
              -advertise="${POD_IP}" \
              -bind=0.0.0.0 \
              -bootstrap-expect=3 \
              -client=0.0.0.0 \
              -config-dir=/consul/config \
              -data-dir=/consul/data \
              -hcl="connect { enabled = true }" \
              -ui \
              -rejoin \
              -retry-join="provider=k8s label_selector=\"app=consul,component=server\"" \
              -server \
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #       - /bin/sh
        #       - -c
        #       - consul intention create wordpress mysql                  
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: data
          mountPath: /consul/data
        - name: config
          mountPath: /consul/config
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        emptyDir: {} 